---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-15.10
    driver:
      box: boxcutter/ubuntu1510
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: centos-7.1
  - name: centos-6.7
  - name: ubuntu-14.04-chef-11
    driver:
      box: bento/ubuntu-14.04
    provisioner:
      require_chef_omnibus: 11.16.4

suites:
  - name: default
    run_list:
      - recipe[snoopy]
  - name: remove
    run_list:
      - recipe[snoopy_test::remove]
